#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# variables
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  path_to_file=$1
  ip=$2
  username=$3
  path_to_ssh_key=$4

  scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
  if [ $? -eq 0 ]; then
    echo "FILE WAS TRANSFERRED SUCCESSFULLY"
  else
    echo "FILE TRANSFER FAILED"
  fi
fi

