#!/usr/bin/env bash
# Installs Nginx

apt-get update
apt-get install -y nginx
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "nginx HTTP"
echo "Hello World" |sudo tee /var/www/html/index.html
service nginx start#!/usr/bin/env bash
# Installs Nginx
 sudo nginx -t

 sudo service nginx reload
